CONFIG_I2S=y
CONFIG_I2C=y
CONFIG_DMA=y
CONFIG_AUDIO=y
CONFIG_AUDIO_CODEC=y
CONFIG_LOG=y
CONFIG_I2S_INFINEON_TX_QUEUE_SIZE=32
CONFIG_SAMPLE_FREQ=16000

CONFIG_MAIN_STACK_SIZE=4096
# CONFIG_NO_OPTIMIZATIONS=y
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
