#ifndef ZEPHYR_INCLUDE_ARCH_TRICORE_REGS_H_
#define ZEPHYR_INCLUDE_ARCH_TRICORE_REGS_H_

/* FIXME replace regs from iLLD */
#define TRICORE_SCU_WDTSCON0	0xf00360f0
#define TRICORE_SCU_WDTSCON1	0xf00360f4
#define TRICORE_SCU_WDTCPU0CON0	0xf0036100
#define TRICORE_SCU_WDTCPU0CON1	0xf0036104

#define TRICORE_CORE_ID		GENMASK(0, 2)
#define TRICORE_PSW_CDE		BIT(7)
#define TRICORE_PSW_GW		BIT(8)
#define TRICORE_PSW_CDC_MSK	GENMASK(6, 0)

#endif
